server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_online?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:Wiigle}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: ZmlsZS1vbmxpbmUtZWRpdGluZy1zZWNyZXQta2V5LTIwMjQtdmVyeS1sb25nLXNlY3JldA==
    expiration-ms: 604800000
